version: '3.7'

services:
  app:
    image: aartgoossens/the-sweat-notebooks:0.6
    container_name: the-sweat-notebooks
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8000:80"
    environment:
      - STRAVA_CLIENT_ID=1337
      - STRAVA_CLIENT_SECRET=abcdefg1234567
      - APP_URL=http://localhost:8000
      - JWT_SECRET=abcdefg1234567
      - ADMIN_IDS=12345678
    volumes:
      - ../data:/data
