FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip
RUN pip install pipenv

RUN mkdir /data

COPY Pipfile Pipfile.lock /app/
WORKDIR /app

RUN pipenv install --system --dev

CMD pytest -s
