version: '3.7'

services:
  app:
    image: fastapi-test
    container_name: fastapi-test
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - ../data:/data
      - ../templates:/data/templates
      - ../output:/data/output
      - ../static:/static
