FROM python:3.7

RUN pip install --upgrade pip
RUN pip install pipenv

RUN mkdir /data

COPY . /app
WORKDIR /app

# COPY Pipfile Pipfile.lock /app/
RUN pipenv install --system

CMD uvicorn app:app --host 0.0.0.0 --port 8000 --reload
