FROM python:3.7

ENV PYTHONDONTWRITEBYTECODE=1

RUN pip install --upgrade pip
RUN pip install pipenv

WORKDIR /app

COPY Pipfile Pipfile.lock /app/
RUN pipenv install --system --dev

WORKDIR /app/app

CMD pytest
