FROM python:3.7

RUN pip install --upgrade pip
RUN pip install pipenv

RUN mkdir /data
COPY Pipfile Pipfile.lock /app/

WORKDIR /app

RUN pipenv install --system

COPY . /app/

EXPOSE 80
CMD uvicorn app:app --host 0.0.0.0 --port 80
