FROM python:3.8

RUN pip install --upgrade pip
RUN pip install pipenv

RUN mkdir /data
COPY Pipfile Pipfile.lock /app/

WORKDIR /app

RUN pipenv install --system

COPY . /app/

EXPOSE 80

CMD gunicorn app:app -w 3 -t 1200 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:80
