version: '3.7'

services:
  app:
    image: fastapi-test-test
    container_name: fastapi-test-test
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ..:/app
      - ../templates:/data/templates
      - ../static:/static
    stdin_open: true
    tty: true
