version: '3.7'

services:
  app:
    image: sweaty-reports-test
    container_name: sweaty-reports-test
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    volumes:
      - ..:/app
    stdin_open: true
    tty: true
